### ISSUE TITLE
Change Favicon from Old one to current Logo SVG

### ISSUE THREAD

**Issue by DARONASS666** [saguarosoftwares/saguarosoftwares.github.io#25]
1. Convert SVG to favicon the same way the current one has been done
2. Add newly made favicon to the repository

**Comment by DARONASS666** [comment]
This is super easy to do, I just couldnt get a good high res conversion online, so i will leave it to you

**Comment by DARONASS666** [comment]
@aghiulez reassigning this to myself, figured out how to generate a nice favicon png thats 512x512.

**Comment by aghiulez** [comment]
FYI the logo as an SVG is in the codebase

**Comment by DARONASS666** [comment]
Without the sun, yeah. i exported one with the sun and put it in the codebase

**Comment by DARONASS666** [comment]
Resolved
